---

# Basic
name: "Vv's"
description: 
"
æ¯ä¸€å¤©éƒ½æ˜¯æ–°çš„å¼€å§‹ğŸ˜Š
å¤©å¤–æœ‰å¤©ï¼Œå±±å¤–æœ‰å±±ï¼Œäººå¤–æœ‰äººï¼Œä¸å¯éª„å‚²è‡ªæ»¡ã€‚
å¤©å„æœ‰ç©ºï¼Œå±±å„æœ‰å³°ï¼Œäººå„æœ‰å¿—ï¼Œä¸å¯å¦„è‡ªè²è–„ã€‚
"

# URL
url: " "
#baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Navigation
nav:
 - name: "About"
   href: "/about"

 - name: "GitHub"
   href: "https://github.com/Vv1222/vv1222.github.com"


# Sass
sass:
 style: :compressed

# Excerpt
excerpt_separator: <!-ex->

#Gems
gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num/"

# Scopes
defaults:
 -
  scope:
   path: ""
   type: "pages"
  values:
   layout: "page"
 -
  scope:
   path: ""
   type: "posts"
  values:
   layout: "post"
---
