---

# Basic
name: "Vv's"
description: "æ¯ä¸€å¤©éƒ½æ˜¯æ–°çš„å¼€å§‹ğŸ˜Š"

# URL
url: " "
#baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Navigation
nav:
 - name: "About"
   href: "/about"

 - name: "GitHub"
   href: "https://github.com/Vv1222/vv1222.github.com"


# Sass
sass:
 style: :compressed

# Excerpt
excerpt_separator: <!-ex->

#Gems
gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num/"

# Scopes
defaults:
 -
  scope:
   path: ""
   type: "pages"
  values:
   layout: "page"
 -
  scope:
   path: ""
   type: "posts"
  values:
   layout: "post"
---
#gitment

gitment:
  enable: true
  mint: true 		# RECOMMEND, A mint on Gitment, to support count, language and proxy_gateway
  count: true 		# Show comments count in post meta area
  lazy: false 		# Comments lazy loading with a button
  cleanly: false 	# Hide 'Powered by ...' on footer, and more
  language: 		# Force language, or auto switch by theme
  github_user: vv1222 	# æ­¤å¤„ - Your Github ID
  github_repo: vv1222.github.com # æ­¤å¤„æ³¨æ„ - The repo you use to store Gitment comments
  client_id: 3c472ea296d4e63b04bb # æ­¤å¤„ - Github client id for the Gitment
  client_secret: 0f7a873b3477f5da1e86e41b1990969f12a5f0af # æ­¤å¤„ - Github access secret token for the Gitment
  proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
  redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled
