---
# # # # # # # # # #
#  K i k o f r i  #
# # # # # # # # # #

# Basic
name: "V v Blog"
description: "æ¯ä¸€å¤©éƒ½æ˜¯æ–°çš„å¼€å§‹ï¼ŒğŸ˜Š"

# URL
url: " "
#baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Navigation
nav:
 - name: "about"
   href: "/about"

 - name: "Git"
   href: "https://github.com/Vv1222/vv1222.github.com"


# Sass
sass:
 style: :compressed

# Excerpt
excerpt_separator: <!-ex->

#Gems
gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num/"

# Scopes
defaults:
 -
  scope:
   path: ""
   type: "pages"
  values:
   layout: "page"
 -
  scope:
   path: ""
   type: "posts"
  values:
   layout: "post"
---
